### ISSUE TITLE
Timeout on GET since 2.0.3

### ISSUE THREAD

**Issue by chrsvl** [koush/ion#450]
Hi koush,

Thanks for this great tool!
But since 2.0.3, I am getting Timeout exceptions on GET requests. I looked into the stack trace when it occurs:
    
    12-30 14:15:52.065  12763-12763/? W/System.err﹕ java.util.concurrent.TimeoutException
    12-30 14:15:52.065  12763-12763/? W/System.err﹕ at com.koushikdutta.async.http.AsyncHttpClient$2.run(AsyncHttpClient.java:247)
    12-30 14:15:52.065  12763-12763/? W/System.err﹕ at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
    12-30 14:15:52.070  12763-12763/? W/System.err﹕ at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
    12-30 14:15:52.070  12763-12763/? W/System.err﹕ at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
    12-30 14:15:52.070  12763-12763/? W/System.err﹕ at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
    12-30 14:15:52.070  12763-12763/? W/System.err﹕ at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)

Do you have any idea what might be the problem?
Thanks in advance :)

**Comment by dany-kun** [comment]
Hi Koush,

My first post here, so first of all, a lot of thanks for this library.

I happen to have the same problem. Everything ok with 2.0.2 but TimeOutException is raised with 2.0.3

For the moment, I got this error only on my calls to the Instagram API, example:

<pre>
01-01 22:37:00.809  30728-30728/com.mypackage I/Instagram_API﹕ (0 ms) https://api.instagram.com/v1/users/self/feed?access_token=xxxxxxxxxxxxx&count=60: Using loader: com.koushikdutta.ion.loader.HttpLoader@42ba71a8
01-01 22:37:30.838  30728-30796/com.mypackage E/Instagram_API﹕ (30029 ms) https://api.instagram.com/v1/users/self/feed?access_token=xxxxxxxxxxxx&count=60: Connection error
01-01 22:37:30.839  30728-30796/com.mypackage E/Instagram_API﹕ null
    java.util.concurrent.TimeoutException
            at com.koushikdutta.async.http.AsyncHttpClient$2.run(AsyncHttpClient.java:247)
            at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)
</pre>

**Comment by koush** [comment]
Are your apps using Google Play Services?

**Comment by koush** [comment]
And what phone is showing this issue?

**Comment by chrsvl** [comment]
We tested on Nexus 5 and Samsung Galaxy mini S4 and faced the same issue. We do not use Google Play services. The problem occured on a GET request to our private servers. The funny thing is a POST (which returns a JSON) works.

**Comment by dany-kun** [comment]
Same here, no Google Play Services and phone is a Wiko Five with Android 4.1.2

**Comment by koush** [comment]
try disabling spdy and let me know if that fixes it it:

Ion.getDefault(context).getHttpClient().getSSLSocketMiddleware().setSpdyEnabled(true);

**Comment by dany-kun** [comment]
Nope, same problem. 
The strange thing is that my first call is working well but the issue occurs when I am chaining the calls (first call -> second call -> ....)

**Comment by koush** [comment]
Can you enable verbose logging and send me a adb logcat?

Ion.getDefault(context).configure().setLogging("Test", Log.VERBOSE);

I thought this may have been a spdy issue, but it may be a https keepalive problem.

**Comment by koush** [comment]
Or email me the log to me@koush.com

**Comment by koush** [comment]
Got your log and was able to reproduce the issue, working on it now.

**Comment by dany-kun** [comment]
Awesome, tks.

**Comment by chrsvl** [comment]
Thanks for your reactiveness @koush

**Comment by koush** [comment]
Fixed here, pushing a new release now.

https://github.com/koush/AndroidAsync/commit/8fccb744e3661434fafafc4c80e0ba8999a169d5

**Comment by dany-kun** [comment]
Confirm it's working. Thanks.

**Comment by subodh-malgonde** [comment]
I am on Ion 2.1.0 and I am still having this issue. Some of my GET calls randomly fail with a TimoutException. I have enabled verbose logging on my calls, here is one such log:

    D/Ion Logs - cities fetch﹕ (0 ms) http://api.peppertap.com/location/v1/cities/: preparing request
    D/Ion Logs - cities fetch﹕ (0 ms) http://api.peppertap.com/location/v1/cities/: preparing request
    I/Ion Logs - cities fetch﹕ (0 ms) http://api.peppertap.com/location/v1/cities/: Using loader:com.koushikdutta.ion.loader.HttpLoader@41c86150
    D/Ion Logs - cities fetch﹕ (0 ms) http://api.peppertap.com/location/v1/cities/: Executing request.
    I/Ion Logs - cities fetch﹕ (9 ms) http://api.peppertap.com/location/v1/cities/: Response may be served from conditional cache
    D/Ion Logs - cities fetch﹕ (9 ms) http://api.peppertap.com/location/v1/cities/: Reusing keep-alive socket
    E/Ion Logs - cities fetch﹕ (30022 ms) http://api.peppertap.com/location/v1/cities/: Connection error
    E/Ion Logs - cities fetch﹕ null
    java.util.concurrent.TimeoutException
            at com.koushikdutta.async.http.AsyncHttpClient$2.run(AsyncHttpClient.java:247)
            at com.koushikdutta.async.AsyncServer.lockAndRunQueue(AsyncServer.java:708)
            at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:725)
            at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:626)
            at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
            at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:568)

**This issue happens only on some calls and usually happens when 2-3 calls happen sequentially.**

**Comment by Nemisis** [comment]
@subodh-malgonde, did you do as @koush instructed [here](https://github.com/koush/ion/issues/450#issuecomment-68512911) and turn off SPDY: 

```java
Ion.getDefault(context).getHttpClient().getSSLSocketMiddleware().setSpdyEnabled(false);
```

That worked for me.

**Comment by subodh-malgonde** [comment]
@Nemisis Yes I had tried doing that, but it dint work for me.

**Comment by Enverbalalic** [comment]
I'm reliably reproducing this issue with spdy disabled on AWS S3

**Comment by koush** [comment]
@Enverbalalic can you give me an emulator setup and url I can use to reproduce this?

**Comment by koush** [comment]
@dany-kun can you give me an emulator configuration and url I can use to reproduce this?

**Comment by koush** [comment]
@subodh-malgonde can you give me an emulator configuration and url I can use to reproduce this?

**Comment by Enverbalalic** [comment]
I could E-Mail you a small test app I put together today that confirms this up to android 8.0. On Android 8.0 this exception is rethrown outside of Ion so a try catch handler will catch it and I can do a retry there, but on Android 4.4 it just crashes "inside" Ion so that an outside try catch, or callback exception never get executed.

**Comment by koush** [comment]
sure

koush@koushikdutta.com
